-------------------------
-- BASE DE DATOS SNAKE --
-------------------------
-- seleccionar base de datos
USE master;
GO

-- eliminar base de datos
DROP DATABASE IF EXISTS SNAKE;

-- crear base de datos
CREATE DATABASE SNAKE 
ON 
(
	NAME = SNAKE_DAT, 
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\snake_dat.mdf', 
	SIZE = 10, 
	MAXSIZE = 50, 
	FILEGROWTH = 5
)
LOG ON 
(
	NAME = SNAKE_LOG, 
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\snake_log.ldf', 
	SIZE = 5MB, 
	MAXSIZE = 25MB, 
	FILEGROWTH = 5MB
);

-- seleccionar base de datos nuevamente
USE SNAKE;
GO


------------------
-- TABLA PERFIL --
------------------
-- crear tabla perfil
CREATE TABLE PERFIL 
(
	ID INT NOT NULL PRIMARY KEY, 
	CODIGO_PERFIL CHAR(5) NOT NULL, 
	NOMBRE_PERFIL VARCHAR(40) NOT NULL, 
	ESTADO CHAR(1) NOT NULL, 
	USER_INSERT VARCHAR(40) NOT NULL, 
	FECHA_INSERT DATETIME NOT NULL, 
	USER_UPDATE VARCHAR(40), 
	FECHA_UPDATE DATETIME 
);

-- registrar datos en tabla perfil
INSERT INTO PERFIL(ID, CODIGO_PERFIL, NOMBRE_PERFIL, ESTADO, USER_INSERT, FECHA_INSERT) VALUES(1, 'ADMIN', 'Administrador', '1', 'admin', GETDATE());
INSERT INTO PERFIL(ID, CODIGO_PERFIL, NOMBRE_PERFIL, ESTADO, USER_INSERT, FECHA_INSERT) VALUES(2, 'SUPER', 'Supervisor', '1', 'admin', GETDATE());
INSERT INTO PERFIL(ID, CODIGO_PERFIL, NOMBRE_PERFIL, ESTADO, USER_INSERT, FECHA_INSERT) VALUES(3, 'OPERA', 'Operador', '1', 'admin', GETDATE());


-------------------
-- TABLA USUARIO --
-------------------
-- crear tabla usuario
CREATE TABLE USUARIO 
(
	ID INT NOT NULL PRIMARY KEY, 
	USERNAME VARCHAR(40) NOT NULL UNIQUE, 
	PASSWORD VARCHAR(32) NOT NULL, 
	NOMBRES VARCHAR(40) NOT NULL, 
	APELLIDOS VARCHAR(40) NOT NULL, 
	TELEFONO VARCHAR(20) NOT NULL, 
	ESTADO CHAR(1) NOT NULL, 
	USER_INSERT VARCHAR(40) NOT NULL, 
	FECHA_INSERT DATETIME NOT NULL, 
	USER_UPDATE VARCHAR(40), 
	FECHA_UPDATE DATETIME, 
	ID_PERFIL INT NOT NULL FOREIGN KEY REFERENCES PERFIL(ID) 
);

-- crear secuencia para tabla usuario
CREATE SEQUENCE SEQ_USUARIO AS INT START WITH 1 INCREMENT BY 1;

-- registrar datos en tabla usuario
INSERT INTO USUARIO(ID, USERNAME, PASSWORD, NOMBRES, APELLIDOS, TELEFONO, ESTADO, USER_INSERT, FECHA_INSERT, ID_PERFIL) VALUES(NEXT VALUE FOR SEQ_USUARIO, 'cesarsantostorres@gmail.com', '123456', 'César Enrique', 'Santos Torres', '989397168', '1', 'admin', GETDATE(), 1);
INSERT INTO USUARIO(ID, USERNAME, PASSWORD, NOMBRES, APELLIDOS, TELEFONO, ESTADO, USER_INSERT, FECHA_INSERT, ID_PERFIL) VALUES(NEXT VALUE FOR SEQ_USUARIO, 'joseantoniodelacruzflores@gmail.com', 'abc', 'José Antonio', 'Delacruz Flores', '987753058', '1', 'admin', GETDATE(), 2);
INSERT INTO USUARIO(ID, USERNAME, PASSWORD, NOMBRES, APELLIDOS, TELEFONO, ESTADO, USER_INSERT, FECHA_INSERT, ID_PERFIL) VALUES(NEXT VALUE FOR SEQ_USUARIO, 'pumablanco@gmail.com', '12345', 'Carlos', 'Lazo Solis', '961872718', '1', 'admin', GETDATE(), 3);

------------------
-- TABLA CATEGORIA --
------------------
-- crear tabla categoria
CREATE TABLE CATEGORIA 
(
	ID INT NOT NULL PRIMARY KEY, 
	NOMBRE_CATEGORIA VARCHAR(40) NOT NULL, 
	ESTADO CHAR(1) NOT NULL, 
	USER_INSERT VARCHAR(40) NOT NULL, 
	FECHA_INSERT DATETIME NOT NULL, 
	USER_UPDATE VARCHAR(40), 
	FECHA_UPDATE DATETIME 
);

-- registrar datos en tabla categoria
INSERT INTO CATEGORIA(ID, NOMBRE_CATEGORIA, ESTADO, USER_INSERT, FECHA_INSERT) VALUES(1, 'Gestion', '1', 'admin', GETDATE());
INSERT INTO CATEGORIA(ID, NOMBRE_CATEGORIA, ESTADO, USER_INSERT, FECHA_INSERT) VALUES(2, 'Mantenimiento', '1', 'admin', GETDATE());
INSERT INTO CATEGORIA(ID, NOMBRE_CATEGORIA, ESTADO, USER_INSERT, FECHA_INSERT) VALUES(3, 'Reportes', '1', 'admin', GETDATE());

------------------
-- TABLA OPCION --
------------------
-- crear tabla opcion
CREATE TABLE OPCION
(
	ID INT NOT NULL PRIMARY KEY, 
	NOMBRE_OPCION VARCHAR(40) NOT NULL, 
	ESTADO CHAR(1) NOT NULL, 
	USER_INSERT VARCHAR(40) NOT NULL, 
	FECHA_INSERT DATETIME NOT NULL, 
	USER_UPDATE VARCHAR(40), 
	FECHA_UPDATE DATETIME, 
	ID_CATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIA(ID), 
	ID_PERFIL INT NOT NULL FOREIGN KEY REFERENCES PERFIL(ID), 
);

-- registrar datos en tabla opcion
INSERT INTO OPCION(ID, NOMBRE_OPCION, ESTADO, USER_INSERT, FECHA_INSERT, ID_CATEGORIA, ID_PERFIL) VALUES(1, 'Reservas', '1', 'admin', GETDATE(), 1, 1);
INSERT INTO OPCION(ID, NOMBRE_OPCION, ESTADO, USER_INSERT, FECHA_INSERT, ID_CATEGORIA, ID_PERFIL) VALUES(2, 'Instrumentos', '1', 'admin', GETDATE(), 1, 2);
INSERT INTO OPCION(ID, NOMBRE_OPCION, ESTADO, USER_INSERT, FECHA_INSERT, ID_CATEGORIA, ID_PERFIL) VALUES(3, 'Costos', '1', 'admin', GETDATE(), 1, 3);

